name: Build Installers for REACHER API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install .
      - name: Build with PyInstaller using spec
        working-directory: web/backend/api
        run: pyinstaller setup.spec
      - name: Create DEB structure
        run: |
          mkdir -p reacher_api_1.0_amd64/DEBIAN
          mkdir -p reacher_api_1.0_amd64/opt/reacher-api
          mkdir -p reacher_api_1.0_amd64/usr/local/bin
          echo "Package: reacher-api
          Version: 1.0
          Section: utils
          Priority: optional
          Architecture: amd64
          Depends: python3 (>= 3.11), python3-tk
          Maintainer: Joshua Boquiren <boquiren@musc.edu>
          Description: REACHER API - A launcher application" > reacher_api_1.0_amd64/DEBIAN/control
          cp -r src/api/dist/reacher-api/* reacher_api_1.0_amd64/opt/reacher-api/
          chmod +x reacher_api_1.0_amd64/opt/reacher-api/reacher-api
          ln -s /opt/reacher-api/reacher-api reacher_api_1.0_amd64/usr/local/bin/reacher-api
      - name: Build DEB package
        run: dpkg-deb --build reacher_api_1.0_amd64
      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: reacher_api_1.0_amd64.deb
          path: reacher_api_1.0_amd64.deb

  release:
    needs: [build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: reacher_api_1.0_amd64.deb
          path: dist/linux
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Linux DEB
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/linux/reacher_api_1.0_amd64.deb
          asset_name: reacher_api_1.0_amd64.deb
          asset_content_type: application/vnd.debian.binary-package
