name: Build Installers for REACHER Dashboard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt
      - name: Build with PyInstaller using spec
        working-directory: src
        run: pyinstaller setup.spec
      - name: Install Inno Setup
        run: choco install innosetup
      - name: Build Installer
        working-directory: src
        run: |
          dir  # Replaced 'ls' with 'dir' for Windows compatibility
          iscc /O"dist" /F"reacher-dashboard-1.0-x64" setup.iss
      - name: Upload Windows installer
        uses: actions/upload-artifact@v4
        with:
          name: reacher-dashboard-1.0-x64.exe
          path: src/dist/reacher-dashboard-1.0-x64.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pyinstaller
      - name: Build with PyInstaller
        working-directory: src
        run: pyinstaller setup.spec
      - name: Create DMG
        run: |
          hdiutil create -volname "REACHER Dashboard Installer" -srcfolder "src/dist/REACHER Dashboard.app" -ov -format UDZO reacher-dashboard-1.0-macos.dmg
      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: reacher-dashboard-1.0-macos.dmg
          path: reacher-dashboard-1.0-macos.dmg

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build with PyInstaller using spec
        working-directory: src
        run: pyinstaller setup.spec
      - name: Create DEB structure
        run: |
          mkdir -p reacher_dashboard_1.0_amd64/DEBIAN
          mkdir -p reacher_dashboard_1.0_amd64/opt/reacher-dashboard
          mkdir -p reacher_dashboard_1.0_amd64/usr/local/bin
          echo "Package: reacher-dashboard
          Version: 1.0
          Section: utils
          Priority: optional
          Architecture: amd64
          Depends: python3 (>= 3.11), python3-tk
          Maintainer: Joshua Boquiren <boquiren@musc.edu>
          Description: REACHER Dashboard - A dashboard application" > reacher_dashboard_1.0_amd64/DEBIAN/control
          cp -r src/dist/reacher-dashboard/* reacher_dashboard_1.0_amd64/opt/reacher-dashboard/
          chmod +x reacher_dashboard_1.0_amd64/opt/reacher-dashboard/reacher-dashboard
          ln -s /opt/reacher-dashboard/reacher-dashboard reacher_dashboard_1.0_amd64/usr/local/bin/reacher-dashboard
      - name: Build DEB package
        run: dpkg-deb --build reacher_dashboard_1.0_amd64
      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: reacher_dashboard_1.0_amd64.deb
          path: reacher_dashboard_1.0_amd64.deb
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: reacher-dashboard-1.0-x64.exe
          path: dist/windows
      - name: Upload Windows Installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/LogisTechLLC/REACHER-Suite/releases/203077386/assets{?name,label}
          asset_path: dist/windows/reacher-dashboard-1.0-x64.exe
          asset_name: reacher-dashboard-1.0-x64.exe
          asset_content_type: application/octet-stream
