name: Build Installers for REACHER Dashboard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: { python-version: '3.11' }
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt
      - name: Build with PyInstaller using spec
        working-directory: src
        run: pyinstaller setup.spec
      - name: Rename EXE
        run: |
          mv dist/reacher-dashboard dist/reacher-dashboard-1.0-x64.exe
      - name: Upload Windows EXE
        uses: actions/upload-artifact@v3
        with:
          name: reacher-dashboard-1.0-x64.exe
          path: dist/reacher-dashboard-1.0-x64.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: { python-version: '3.11' }
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pyinstaller -r requirements.txt
      - name: Build with PyInstaller using spec
        working-directory: src
        run: pyinstaller setup.spec
      - name: Create APP bundle
        run: |
          mkdir -p "REACHER Dashboard.app/Contents/MacOS"
          mkdir -p "REACHER Dashboard.app/Contents/Resources"
          mv dist/reacher-dashboard "REACHER Dashboard.app/Contents/MacOS/REACHER Dashboard"
      - name: Create Info.plist
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN">
          <plist version="1.0">
          <dict>
            <key>CFBundleExecutable</key>
            <string>REACHER Dashboard</string>
            <key>CFBundleIdentifier</key>
            <string>com.yourname.reacher-dashboard</string>
            <key>CFBundleName</key>
            <string>REACHER Dashboard</string>
            <key>CFBundleVersion</key>
            <string>1.0</string>
          </dict>
          </plist>' > "REACHER Dashboard.app/Contents/Info.plist"
      - name: Create DMG
        run: |
          hdiutil create -volname "REACHER Dashboard Installer" -srcfolder "REACHER Dashboard.app" -ov -format UDZO reacher-dashboard-1.0-macos.dmg
      - name: Upload macOS DMG
        uses: actions/upload-artifact@v3
        with:
          name: reacher-dashboard-1.0-macos.dmg
          path: reacher-dashboard-1.0-macos.dmg

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: { python-version: '3.11' }
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-tk
      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pyinstaller -r requirements.txt
      - name: Build with PyInstaller using spec
        working-directory: src
        run: pyinstaller setup.spec
      - name: Create DEB structure
        run: |
          mkdir -p reacher_dashboard_1.0_amd64/DEBIAN
          mkdir -p reacher_dashboard_1.0_amd64/usr/local/bin
          echo "Package: reacher-dashboard
          Version: 1.0
          Section: utils
          Priority: optional
          Architecture: amd64
          Depends: python3 (>= 3.11), python3-tk
          Maintainer: Your Name <your.email@example.com>
          Description: REACHER Dashboard - A dashboard application" > reacher_dashboard_1.0_amd64/DEBIAN/control
          cp dist/reacher-dashboard reacher_dashboard_1.0_amd64/usr/local/bin/reacher-dashboard
          chmod +x reacher_dashboard_1.0_amd64/usr/local/bin/reacher-dashboard
      - name: Build DEB
        run: dpkg-deb --build reacher_dashboard_1.0_amd64
      - name: Upload Linux DEB
        uses: actions/upload-artifact@v3
        with:
          name: reacher_dashboard_1.0_amd64.deb
          path: reacher_dashboard_1.0_amd64.deb
