name: Build Installers

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: pyinstaller setup.spec

      - name: Install Inno Setup
        run: choco install innosetup -y
        shell: cmd

      - name: Build Windows installer
        run: '"C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe" setup.iss'
        shell: cmd

      - name: Upload Windows installer
        uses: actions/upload-artifact@v3
        with:
          name: reacher_suite_windows_installer
          path: dist/reacher_suite_setup.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: pyinstaller setup.spec

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Build macOS installer
        run: |
          create-dmg \
            --volname "REACHER Suite" \
            --window-pos 200 120 \
            --window-size 500 300 \
            --icon-size 100 \
            --app-drop-link 400 120 \
            "reacher_suite.dmg" \
            "dist/reacher_suite.app"

      - name: Upload macOS installer
        uses: actions/upload-artifact@v4
        with:
          name: reacher_suite_macos_installer
          path: reacher_suite.dmg

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: pyinstaller setup.spec

      - name: Install makeself
        run: sudo apt-get update && sudo apt-get install -y makeself

      - name: Create Linux installer
        run: |
          mkdir temp_installer
          cp dist/reacher_suite temp_installer/
          cp install.sh temp_installer/
          chmod +x temp_installer/install.sh
          makeself temp_installer reacher_suite.run "REACHER Suite Installer" ./install.sh

      - name: Upload Linux installer
        uses: actions/upload-artifact@v4
        with:
          name: reacher_suite_linux_installer
          path: reacher_suite.run
